server {
    listen 80;
    server_name nguyen-thanh-nam.rikkeieducation.com;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain application/json application/javascript text/css application/xml;
    gzip_min_length 1000;

    # Gioi han dung luong upload file
    client_max_body_size 10M;

    # Proxy Backend API
    location /api/ {
        proxy_pass http://backend:9999/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_buffering on;
    }

    # Default response (khong co FE)
    location / {
        return 200 '{"message": "Rikkei Backend API is running. Use /api/ endpoint."}';
        add_header Content-Type application/json;
    }
}
