# PostgreSQL via Docker Network
spring.datasource.url=jdbc:postgresql://postgres:5432/rikkei_prod
spring.datasource.username=rikkei
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Server
server.port=9999

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary
cloudinary.cloud-name=dt0n424nb
cloudinary.api-key=375722427327395
cloudinary.api-secret=15X8KTlTGz4jP59x9LgnJKwle6o

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nambun265@gmail.com
spring.mail.password=xjwf ylep btbo sciz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Management & Health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
